{
 "title": "test",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU LA",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\"}",
     "legendFormat": "LA 1"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\"}",
     "legendFormat": "LA 5"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\"}",
     "legendFormat": "LA 15"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\"}/1024/1024"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"nodeexporter:9100\",mountpoint=\"/\",fstype!~\"tmpfs|fuse.lxcfs\"}/1024/1024/1024"
    }
   ]
  }
 ]
}